configfile: "config/config.yml"

include: "rules/common.smk"
include: "rules/download.smk"
include: "rules/extract.smk"
include: "rules/aggregate.smk"

localrules: all, download_stacks, extract, aggregate_broad # , aggregate_sources

rule all:
    input: "results/aggregated/aggregate.txt"

rule aggregate:
    input:
        expand("results/checkpoints/rechunk_broad/{source}.ckpt", source=sources)
    output:
        "results/aggregated/aggregate.txt"
    shell:
        "echo {input} > {output}"
